config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    def hello
      render html: "hello, world!"
    end
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @random = rand(4)
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Kevin Kim's Webpage!"
      redirect_to @user    
    else
      render 'new' 
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
     base_title = ""
     if page_title.empty?
       base_title
     else
       "#{base_title} | #{page_title}"
     end
    end
    def message(random)
        message = {0=> 'You need to run away', 1=> 'You are thirsty.', 2=> 'You need to rest.', 3=> 'You need to focus.'}
        message[random]
      end
   end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Personal Project from the tutorial</a>
    by <a href="http://www.kimdream.com">Kevin Kim</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-color">
  <div class="container">
    <%= link_to "KEVIN KIM", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path, id: "custom"%></li>
        <li><%= link_to "Help",    help_path, id: "custom" %></li>
        <li><%= link_to "About", about_path, id: "custom" %></li>
        <li><%= link_to "Log in", signup_path, id: "custom" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Kevin's Self Website</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div di="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

<div class="box">
  <%= link_to image_tag("rails-1.jpg", alt: "kevin") %>
  
  <p>
  &emsp;&emsp;&emsp;I am currently in my sophomore year at Grinnell College pursuing Computer Science and Statistics.
I have a keen interst in the field of technology and design. 
I am currently pursuing this interest by working on projects that combine these areas. 
<br/><br/>
##Technical Skill Showcase
<br/><br/>
&emsp;&emsp;&emsp;This is a dynamic, database-backed web app that is developed using Ruby on Rail framework, strictly folllowing MVC design pattern. My development skills include unit testing, partials on the view, modeling database, etc. The development proces started with Behavioral Driven Development (BDD) and then mostly followed Testing Driven Development (TDD). It has a sign-up page to store properly formated input and returns error message if user provides invaid input.
  </p>
</div>
<a href="https://www.kimdream.com"><em> Contact me</em>
</a>
to know more about me.

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

  
</p>
<div class="box">
  <%= link_to image_tag("rails-1.jpg", alt: "kevin") %>
  <p>
  &emsp;&emsp;&emsp;To get help from me, respect my photos and 
  <a href="https://www.kimdream.com"><em> contact me</em>
  </a>.
  I am always ready to help you if you want to learn more about this website. 
  Help page usually contains the most commonly sought questions. 
  But, I don't think that will be helpful.
  <br/><br/>
  &emsp;&emsp;&emsp;For simple questions, just contact me directly. There is me everwhere in this page.
  Think about what I wish I can do for me. If there is a problem with an article about myself or if I spot
  a problem with an image of myself, I will make sure I improve on it. But, remember to appreciate this website since this is probably Kevin.
  </p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome</h1>

  <h2>
    This is where you can remind who you are and what you are feeling.
  </h2>
  <p><%=message(@random)%></p>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="box">
  <%= link_to image_tag("rails-1.jpg", alt: "kevin") %>
  <p>
  &emsp;&emsp;&emsp;I am currently in my sophomore year at Grinnell College pursuing Computer Science and Statistics.
I have a keen interst in the field of technology and design. 
I am currently pursuing this interest by working on projects that combine these areas. 
<br/><br/>
&emsp;&emsp;&emsp;I previously have developed a website that enables students to promote their student organizations 
and have built an iOS application for college news. 
I aim to become a software engineer that enable users to engage with the community through technology. 
Now go ahead and learn more about me.
  </p>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name , class: 'form-control' %>

      <%= f.label:email%>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email%>